<a href="https://www.kaggle.com/code/mcadriaans/famous-paintings-sql?scriptVersionId=168318165" target="_blank"><img align="left" alt="Kaggle" title="Open in Kaggle" src="https://kaggle.com/static/images/open-in-kaggle.svg"></a>

In [1]:
# This Python 3 environment comes with many helpful analytics libraries installed
# It is defined by the kaggle/python Docker image: https://github.com/kaggle/docker-python
# For example, here's several helpful packages to load

import numpy as np # linear algebra
import pandas as pd # data processing, CSV file I/O (e.g. pd.read_csv)

# Input data files are available in the read-only "../input/" directory
# For example, running this (by clicking run or pressing Shift+Enter) will list all files under the input directory

import os
for dirname, _, filenames in os.walk('/kaggle/input'):
    for filename in filenames:
        print(os.path.join(dirname, filename))

# You can write up to 20GB to the current directory (/kaggle/working/) that gets preserved as output when you create a version using "Save & Run All" 
# You can also write temporary files to /kaggle/temp/, but they won't be saved outside of the current session

/kaggle/input/famous-paintings/subject.csv
/kaggle/input/famous-paintings/museum_hours.csv
/kaggle/input/famous-paintings/artist.csv
/kaggle/input/famous-paintings/museum.csv
/kaggle/input/famous-paintings/product_size.csv
/kaggle/input/famous-paintings/image_link.csv
/kaggle/input/famous-paintings/work.csv
/kaggle/input/famous-paintings/canvas_size.csv

In [2]:
# This package integrates SQL with IPython Notebook
!pip install ipython-sql

Requirement already satisfied: ipython-sql in /opt/conda/lib/python3.10/site-packages (0.5.0)
Requirement already satisfied: prettytable in /opt/conda/lib/python3.10/site-packages (from ipython-sql) (3.9.0)
Requirement already satisfied: ipython in /opt/conda/lib/python3.10/site-packages (from ipython-sql) (8.20.0)
Requirement already satisfied: sqlalchemy>=2.0 in /opt/conda/lib/python3.10/site-packages (from ipython-sql) (2.0.25)
Requirement already satisfied: sqlparse in /opt/conda/lib/python3.10/site-packages (from ipython-sql) (0.4.4)
Requirement already satisfied: six in /opt/conda/lib/python3.10/site-packages (from ipython-sql) (1.16.0)
Requirement already satisfied: ipython-genutils in /opt/conda/lib/python3.10/site-packages (from ipython-sql) (0.2.0)
Requirement already satisfied: typing-extensions>=4.6.0 in /opt/conda/lib/python3.10/site-packages (from sqlalchemy>=2.0->ipython-sql) (4.9.0)
Requirement already satisfied: greenlet!=0.4.17 in /opt/conda/lib/python3.10/site-packages (from sqlalchemy>=2.0->ipython-sql) (3.0.3)
Requirement already satisfied: decorator in /opt/conda/lib/python3.10/site-packages (from ipython->ipython-sql) (5.1.1)
Requirement already satisfied: jedi>=0.16 in /opt/conda/lib/python3.10/site-packages (from ipython->ipython-sql) (0.19.1)
Requirement already satisfied: matplotlib-inline in /opt/conda/lib/python3.10/site-packages (from ipython->ipython-sql) (0.1.6)
Requirement already satisfied: prompt-toolkit<3.1.0,>=3.0.41 in /opt/conda/lib/python3.10/site-packages (from ipython->ipython-sql) (3.0.42)
Requirement already satisfied: pygments>=2.4.0 in /opt/conda/lib/python3.10/site-packages (from ipython->ipython-sql) (2.17.2)
Requirement already satisfied: stack-data in /opt/conda/lib/python3.10/site-packages (from ipython->ipython-sql) (0.6.2)
Requirement already satisfied: traitlets>=5 in /opt/conda/lib/python3.10/site-packages (from ipython->ipython-sql) (5.9.0)
Requirement already satisfied: exceptiongroup in /opt/conda/lib/python3.10/site-packages (from ipython->ipython-sql) (1.2.0)
Requirement already satisfied: pexpect>4.3 in /opt/conda/lib/python3.10/site-packages (from ipython->ipython-sql) (4.8.0)
Requirement already satisfied: wcwidth in /opt/conda/lib/python3.10/site-packages (from prettytable->ipython-sql) (0.2.13)
Requirement already satisfied: parso<0.9.0,>=0.8.3 in /opt/conda/lib/python3.10/site-packages (from jedi>=0.16->ipython->ipython-sql) (0.8.3)
Requirement already satisfied: ptyprocess>=0.5 in /opt/conda/lib/python3.10/site-packages (from pexpect>4.3->ipython->ipython-sql) (0.7.0)
Requirement already satisfied: executing>=1.2.0 in /opt/conda/lib/python3.10/site-packages (from stack-data->ipython->ipython-sql) (2.0.1)
Requirement already satisfied: asttokens>=2.1.0 in /opt/conda/lib/python3.10/site-packages (from stack-data->ipython->ipython-sql) (2.4.1)
Requirement already satisfied: pure-eval in /opt/conda/lib/python3.10/site-packages (from stack-data->ipython->ipython-sql) (0.2.2)

In [3]:
# Provides a source od database connectivity
from sqlalchemy import create_engine

# Working with SQLite database in Python
import sqlite3

# <font color= indigo>Data Preparation</font>

## <font color= darkcyan>Subject data</font>

### Load data

In [4]:
df_subject = pd.read_csv('/kaggle/input/famous-paintings/subject.csv')
df_subject.head()

   work_id     subject
0   160228  Still-Life
1   160236  Still-Life
2   160244  Still-Life
3   160252  Still-Life
4   160260  Still-Life

In [5]:
# The dimensionality of the DataFrame
df_subject.shape

(6771, 2)

In [6]:
# Display information about the DataFrame
df_subject.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 6771 entries, 0 to 6770
Data columns (total 2 columns):
 #   Column   Non-Null Count  Dtype
---  ------   --------------  -----
 0   work_id  6771 non-null   int64
 1   subject  6771 non-null   object
dtypes: int64(1), object(1)
memory usage: 105.9+ KB

### <font color=darkslategray><u>Data Cleaning</u></font>

#### Check for duplicates

In [7]:
# Find the total number of duplicate rows in the DataFrame
df_subject.duplicated().sum()

59

In [8]:
# Remove duplicates
df_subject = df_subject.drop_duplicates()
df_subject.shape

(6712, 2)

#### Missing Values

In [9]:
df_subject.isnull().sum()

work_id    0
subject    0
dtype: int64

## <font color= darkcyan> Museum Hours</font>

### Load data

In [10]:
df_museum_hrs = pd.read_csv('/kaggle/input/famous-paintings/museum_hours.csv')
df_museum_hrs.head()

   museum_id        day      open     close
0         30     Sunday  10:30:AM  05:30:PM
1         30     Monday  10:30:AM  05:30:PM
2         30    Tuesday  10:30:AM  05:30:PM
3         30  Wednesday  10:30:AM  05:30:PM
4         30    Thusday  10:30:AM  05:30:PM

In [11]:
# The dimensionality of the DataFrame
df_museum_hrs.shape

(351, 4)

In [12]:
df_museum_hrs.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 351 entries, 0 to 350
Data columns (total 4 columns):
 #   Column     Non-Null Count  Dtype
---  ------     --------------  -----
 0   museum_id  351 non-null    int64
 1   day        351 non-null    object
 2   open       351 non-null    object
 3   close      351 non-null    object
dtypes: int64(1), object(3)
memory usage: 11.1+ KB

### <font color=darkslategray><u>Data Cleaning</u></font>

#### Check for duplicates

In [13]:
df_museum_hrs.duplicated().sum()

1

In [14]:
df_museum_hrs = df_museum_hrs.drop_duplicates()
df_museum_hrs.shape

(350, 4)

#### Missing Values

In [15]:
df_museum_hrs.isnull().sum()

museum_id    0
day          0
open         0
close        0
dtype: int64

## <font color= darkcyan> Artist</font>

### Load data

In [16]:
df_artist = pd.read_csv('/kaggle/input/famous-paintings/artist.csv')
df_artist.head()

,artist_id,full_name,first_name,middle_names,last_name,nationality,style,birth,death
0,500,Pierre-Auguste Renoir,Pierre,Auguste,Renoir,French,Impressionist,1841,1919
1,501,Alexandre Cabanel,Alexandre,NaN,Cabanel,French,Classicist,1823,1889
2,502,James Ensor,James,NaN,Ensor,Belgian,Expressionist,1860,1949
3,503,Maximilien Luce,Maximilien,NaN,Luce,French,Pointillist,1858,1941
4,504,August Macke,August,NaN,Macke,German,Expressionist,1887,1914

In [17]:
df_artist.shape

(421, 9)

In [18]:
df_artist.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 421 entries, 0 to 420
Data columns (total 9 columns):
 #   Column        Non-Null Count  Dtype
---  ------        --------------  -----
 0   artist_id     421 non-null    int64
 1   full_name     421 non-null    object
 2   first_name    421 non-null    object
 3   middle_names  148 non-null    object
 4   last_name     421 non-null    object
 5   nationality   421 non-null    object
 6   style         421 non-null    object
 7   birth         421 non-null    int64
 8   death         421 non-null    int64
dtypes: int64(3), object(6)
memory usage: 29.7+ KB

### <font color=darkslategray><u>Data Cleaning</u></font>

#### Check for duplicates

In [19]:
df_artist.duplicated().sum()

0

#### Missing Values

In [20]:
df_artist.isnull().sum()

artist_id         0
full_name         0
first_name        0
middle_names    273
last_name         0
nationality       0
style             0
birth             0
death             0
dtype: int64

In [21]:
df_artist_missing_vals = df_artist.isnull().sum().reset_index()
df_artist_missing_vals.columns = ['columns', 'nr_of_missingValues']
df_artist_missing_vals['perc_of_missingValues'] = (df_artist_missing_vals['nr_of_missingValues']/df_artist.shape[0]* 100).round(2)
df_artist_missing_vals[df_artist_missing_vals['perc_of_missingValues'] != 0]

        columns  nr_of_missingValues  perc_of_missingValues
3  middle_names                  273                  64.85

In [22]:
# Remove 'middle_names' column
df_artist.drop('middle_names', axis=1 , inplace=True)
df_artist.columns

Index(['artist_id', 'full_name', 'first_name', 'last_name', 'nationality',
       'style', 'birth', 'death'],
      dtype='object')

## <font color=darkcyan>Museum</font>

### Load data

In [23]:
df_museum = pd.read_csv('/kaggle/input/famous-paintings/museum.csv')
df_museum.head()

,museum_id,name,address,city,state,postal,country,phone,url
0,30,The Museum of Modern Art,11 W 53rd St,New York,NY,10019,USA,+1 212 708-9400,https://www.moma.org/
1,31,Pushkin State Museum of Fine Arts,12 Ulitsa Volkhonka,Moscow,NaN,119019,Russia,+7 495 697-95-78,https://pushkinmuseum.art/
2,32,National Gallery of Victoria,180 St Kilda Rd,Melbourne,Victoria,3004,Australia,+61 (0)3 8620 2222,https://www.ngv.vic.gov.au/
3,33,São Paulo Museum of Art,"Av. Paulista, 1578 - Bela Vista",São Paulo,NaN,01310-200,Brazil,+55 11 3149-5959,https://masp.org.br/
4,34,The State Hermitage Museum,Palace Square,2,Sankt-Peterburg,190000,Russia,7 812 710-90-79,https://www.hermitagemuseum.org/wps/portal/her...

In [24]:
df_museum.shape

(57, 9)

In [25]:
df_museum.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 57 entries, 0 to 56
Data columns (total 9 columns):
 #   Column     Non-Null Count  Dtype
---  ------     --------------  -----
 0   museum_id  57 non-null     int64
 1   name       57 non-null     object
 2   address    57 non-null     object
 3   city       57 non-null     object
 4   state      38 non-null     object
 5   postal     50 non-null     object
 6   country    57 non-null     object
 7   phone      57 non-null     object
 8   url        57 non-null     object
dtypes: int64(1), object(8)
memory usage: 4.1+ KB

### <font color=darkslategray><u>Data Cleaning</u></font>

#### Check for duplicates

In [26]:
df_museum.duplicated().sum()

0

#### Missing Values

In [27]:
df_museum.isnull().sum()

museum_id     0
name          0
address       0
city          0
state        19
postal        7
country       0
phone         0
url           0
dtype: int64

In [28]:
# Remove columns with missing values
df_museum.drop(['state', 'postal'], axis=1 , inplace=True)
df_museum.columns

Index(['museum_id', 'name', 'address', 'city', 'country', 'phone', 'url'], dtype='object')

## <font color=darkcyan>Product Size </font>

### Load data

In [29]:
df_productSize = pd.read_csv('/kaggle/input/famous-paintings/product_size.csv')
df_productSize.head()

   work_id size_id  sale_price  regular_price
0   160228      24          85             85
1   160228      30          95             95
2   160236      24          85             85
3   160236      30          95             95
4   160244      24          85             85

In [30]:
df_productSize.shape

(110347, 4)

In [31]:
df_productSize.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 110347 entries, 0 to 110346
Data columns (total 4 columns):
 #   Column         Non-Null Count   Dtype
---  ------         --------------   -----
 0   work_id        110347 non-null  int64
 1   size_id        110347 non-null  object
 2   sale_price     110347 non-null  int64
 3   regular_price  110347 non-null  int64
dtypes: int64(3), object(1)
memory usage: 3.4+ MB

### <font color=darkslategray><u>Data Cleaning</u></font>

### Update datatype for size_id

In [32]:
df_productSize['size_id'].unique()

array(['24', '30', '3024', '3226', '3629', '4030', '4836', '6048', '6854',
       '3624', '4630', '5436', '6040', '7248', '20', '2430', '2632',
       '2936', '3040', '3648', '4860', '5468', '36', '2436', '3046',
       '3654', '4060', '4872', '1620', '2024', '1624', '2030', '40', '48',
       '4020', '4824', '6030', '7236', '8040', '9648', '2424', '3030',
       '3636', '4040', '4848', '6060', '2016', '2420', '2020', '2416',
       '3020', '#VALUE!', '1632', '2040', '2448', '3060', '3672', '4080',
       '16.223', '28.836', '39.532', '3216', '56', '3628.7', '32.226',
       '3225.5', '4896', '3218', '32.426', '3239.8', '2936.5', '3225.6',
       '3223.7', '36.329', '36.432', '36.532', '27.326', '31.944',
       '28.525', '3232', '57.745', '4434', '3225.9', '2417.8', '7171',
       '5136.5', '5439.4', '22.43', '26.232', '2429', '50.635', '39.632',
       '3225.8', '3730', '3627', '35.652', '4235.5', '5062.6', '2823.2',
       '2419.7', '25.632', '37.428', '2921.7', '2921.5', '2639.8',
       '32.251', '31.525', '5936.2', '2923.6', '2923.7', '25.732',
       '2632.1', '57.542', '3536.5', '38.531', '5691.2', '3225.7',
       '32.326', '39.526', '23.529', '4023.7', '36.429', '36.326',
       '36.829', '32.524', '36.529', '39.435', '79.163', '36.626',
       '3239.4', '39.429', '5844.9', '3239.2', '57.545', '25.832',
       '32.332', '28.824', '3628.6', '4635.4', '4635', '2632.3', '50.465',
       '4835.8', '19.524', '28.936', '3246', '3628.5', '44.534', '3628.8',
       '45.835', '28.537', '32.126', '28.724', '3729.3', '37.53',
       '29.137', '3527.6', '2227.2', '4532', '3123.6', '3729.9', '26.332',
       '2936.6', '35.628'], dtype=object)

In [33]:
# Convert the column to numeric, errors='coerce' will set non-numeric values to NaN
df_productSize['size_id'] = pd.to_numeric(df_productSize['size_id'], errors='coerce')
df_productSize['size_id'].unique()

array([  24.   ,   30.   , 3024.   , 3226.   , 3629.   , 4030.   ,
       4836.   , 6048.   , 6854.   , 3624.   , 4630.   , 5436.   ,
       6040.   , 7248.   ,   20.   , 2430.   , 2632.   , 2936.   ,
       3040.   , 3648.   , 4860.   , 5468.   ,   36.   , 2436.   ,
       3046.   , 3654.   , 4060.   , 4872.   , 1620.   , 2024.   ,
       1624.   , 2030.   ,   40.   ,   48.   , 4020.   , 4824.   ,
       6030.   , 7236.   , 8040.   , 9648.   , 2424.   , 3030.   ,
       3636.   , 4040.   , 4848.   , 6060.   , 2016.   , 2420.   ,
       2020.   , 2416.   , 3020.   ,      nan, 1632.   , 2040.   ,
       2448.   , 3060.   , 3672.   , 4080.   ,   16.223,   28.836,
         39.532, 3216.   ,   56.   , 3628.7  ,   32.226, 3225.5  ,
       4896.   , 3218.   ,   32.426, 3239.8  , 2936.5  , 3225.6  ,
       3223.7  ,   36.329,   36.432,   36.532,   27.326,   31.944,
         28.525, 3232.   ,   57.745, 4434.   , 3225.9  , 2417.8  ,
       7171.   , 5136.5  , 5439.4  ,   22.43 ,   26.232, 2429.   ,
         50.635,   39.632, 3225.8  , 3730.   , 3627.   ,   35.652,
       4235.5  , 5062.6  , 2823.2  , 2419.7  ,   25.632,   37.428,
       2921.7  , 2921.5  , 2639.8  ,   32.251,   31.525, 5936.2  ,
       2923.6  , 2923.7  ,   25.732, 2632.1  ,   57.542, 3536.5  ,
         38.531, 5691.2  , 3225.7  ,   32.326,   39.526,   23.529,
       4023.7  ,   36.429,   36.326,   36.829,   32.524,   36.529,
         39.435,   79.163,   36.626, 3239.4  ,   39.429, 5844.9  ,
       3239.2  ,   57.545,   25.832,   32.332,   28.824, 3628.6  ,
       4635.4  , 4635.   , 2632.3  ,   50.465, 4835.8  ,   19.524,
         28.936, 3246.   , 3628.5  ,   44.534, 3628.8  ,   45.835,
         28.537,   32.126,   28.724, 3729.3  ,   37.53 ,   29.137,
       3527.6  , 2227.2  , 4532.   , 3123.6  , 3729.9  ,   26.332,
       2936.6  ,   35.628])

In [34]:
# Remove all rows where 'size_id' has a NaN value
df_productSize = df_productSize.dropna(subset = ['size_id'])

In [35]:
# Filter out non-integer values
df_productSize= df_productSize[df_productSize['size_id'].apply(lambda x: x.is_integer() if pd.notnull(x) else False)]

In [36]:
# Convert column to an integer data type
df_productSize['size_id'] = df_productSize['size_id'].astype(int)

In [37]:
df_productSize.info()

<class 'pandas.core.frame.DataFrame'>
Index: 110019 entries, 0 to 110346
Data columns (total 4 columns):
 #   Column         Non-Null Count   Dtype
---  ------         --------------   -----
 0   work_id        110019 non-null  int64
 1   size_id        110019 non-null  int64
 2   sale_price     110019 non-null  int64
 3   regular_price  110019 non-null  int64
dtypes: int64(4)
memory usage: 4.2 MB

In [38]:
# Display the unique size_ids
df_productSize['size_id'].unique()

array([  24,   30, 3024, 3226, 3629, 4030, 4836, 6048, 6854, 3624, 4630,
       5436, 6040, 7248,   20, 2430, 2632, 2936, 3040, 3648, 4860, 5468,
         36, 2436, 3046, 3654, 4060, 4872, 1620, 2024, 1624, 2030,   40,
         48, 4020, 4824, 6030, 7236, 8040, 9648, 2424, 3030, 3636, 4040,
       4848, 6060, 2016, 2420, 2020, 2416, 3020, 1632, 2040, 2448, 3060,
       3672, 4080, 3216,   56, 4896, 3218, 3232, 4434, 7171, 2429, 3730,
       3627, 4635, 3246, 4532])

#### Check for duplicates

In [39]:
df_productSize.duplicated().sum()

687

In [40]:
df_productSize = df_productSize.drop_duplicates()
df_productSize.shape

(109332, 4)

#### Missing Values

In [41]:
df_productSize.isnull().sum()

work_id          0
size_id          0
sale_price       0
regular_price    0
dtype: int64

## <font color=darkcyan>Image Link </font>

### Load data

In [42]:
df_imageLink = pd.read_csv('/kaggle/input/famous-paintings/image_link.csv')
df_imageLink.head()

,work_id,url,thumbnail_small_url,thumbnail_large_url
0,181978,https://v5.airtableusercontent.com/v1/15/15/16...,https://v5.airtableusercontent.com/v1/15/15/16...,https://v5.airtableusercontent.com/v1/15/15/16...
1,173188,https://v5.airtableusercontent.com/v1/15/15/16...,https://v5.airtableusercontent.com/v1/15/15/16...,https://v5.airtableusercontent.com/v1/15/15/16...
2,194065,https://v5.airtableusercontent.com/v1/15/15/16...,https://v5.airtableusercontent.com/v1/15/15/16...,https://v5.airtableusercontent.com/v1/15/15/16...
3,129337,https://v5.airtableusercontent.com/v1/15/15/16...,https://v5.airtableusercontent.com/v1/15/15/16...,https://v5.airtableusercontent.com/v1/15/15/16...
4,141073,https://v5.airtableusercontent.com/v1/15/15/16...,https://v5.airtableusercontent.com/v1/15/15/16...,https://v5.airtableusercontent.com/v1/15/15/16...

In [43]:
df_imageLink.shape

(14775, 4)

In [44]:
df_imageLink.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 14775 entries, 0 to 14774
Data columns (total 4 columns):
 #   Column               Non-Null Count  Dtype
---  ------               --------------  -----
 0   work_id              14775 non-null  int64
 1   url                  14775 non-null  object
 2   thumbnail_small_url  14773 non-null  object
 3   thumbnail_large_url  14773 non-null  object
dtypes: int64(1), object(3)
memory usage: 461.8+ KB

### <font color=darkslategray><u>Data Cleaning</u></font>

#### Check for duplicates

In [45]:
df_imageLink.duplicated().sum()

60

In [46]:
df_productSize = df_productSize.drop_duplicates()
df_productSize.shape

(109332, 4)

#### Missing Values

In [47]:
df_imageLink.isnull().sum()

work_id                0
url                    0
thumbnail_small_url    2
thumbnail_large_url    2
dtype: int64

In [48]:
# Remove all rows in specified columns where atleast 1 value is missing
df_imageLink.loc[:, ['thumbnail_small_url','thumbnail_large_url']].dropna(inplace=True)

## <font color=darkcyan>Work </font>

### Load data

In [49]:
df_work = pd.read_csv('/kaggle/input/famous-paintings/work.csv')
df_work.head()

,work_id,name,artist_id,style,museum_id
0,160228,Still Life with Flowers and a Watch,615,Baroque,43.0
1,160236,Still Life with Fruit and a Beaker on a Cock's...,615,Baroque,43.0
2,160244,Still Life with Fruit and a Goldfinch,615,Baroque,43.0
3,160252,Still Life with Fruit and Oysters,615,Baroque,43.0
4,160260,"Still Life with Fruit, Oysters, and a Porcelai...",615,Baroque,43.0

In [50]:
df_work.shape

(14776, 5)

In [51]:
df_work.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 14776 entries, 0 to 14775
Data columns (total 5 columns):
 #   Column     Non-Null Count  Dtype
---  ------     --------------  -----
 0   work_id    14776 non-null  int64
 1   name       14776 non-null  object
 2   artist_id  14776 non-null  int64
 3   style      13490 non-null  object
 4   museum_id  4553 non-null   float64
dtypes: float64(1), int64(2), object(2)
memory usage: 577.3+ KB

### <font color=darkslategray><u>Data Cleaning</u></font>

#### Check for duplicates

In [52]:
df_work.duplicated().sum()

60

In [53]:
df_work = df_work.drop_duplicates()
df_work.shape

(14716, 5)

#### Missing Values

In [54]:
df_work.isnull().sum()

work_id          0
name             0
artist_id        0
style         1228
museum_id    10163
dtype: int64

In [55]:
df_work_missing_vals = df_work.isnull().sum().reset_index()
df_work_missing_vals.columns = ['columns', 'nr_of_missingValues']
df_work_missing_vals['perc_of_missingValues'] = (df_work_missing_vals['nr_of_missingValues']/df_work.shape[0]* 100).round(2)
df_work_missing_vals[df_work_missing_vals['perc_of_missingValues'] != 0]

     columns  nr_of_missingValues  perc_of_missingValues
3      style                 1228                   8.34
4  museum_id                10163                  69.06

In [56]:
# Fill missing values on style column with 'Other'
df_work['style'] = df_work['style'].fillna(value='Other')
df_work['style'].unique()

array(['Baroque', 'Other', 'Neo-Classicism', 'Renaissance',
       'Expressionism', 'American Landscape', 'Post-Impressionism',
       'Classicism', 'Avant-Garde', 'Impressionism', 'Cubism', 'Rococo',
       'Realism', 'Fauvism', 'Nabi', 'Symbolism', 'Naturalism',
       'American Art', 'Romanticism', 'Orientalism', 'Art Nouveau',
       'Surrealism', 'Pointillism', 'Japanese Art'], dtype=object)

## <font color=darkcyan>Canvas Size </font>

### Load data

In [57]:
df_canvasSize = pd.read_csv('/kaggle/input/famous-paintings/canvas_size.csv')
df_canvasSize.head()

   size_id  width  height          label
0       20     20     NaN  20" Long Edge
1       24     24     NaN  24" Long Edge
2       30     30     NaN  30" Long Edge
3       36     36     NaN  36" Long Edge
4       40     40     NaN  40" Long Edge

In [58]:
df_canvasSize.shape

(200, 4)

In [59]:
df_canvasSize.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 200 entries, 0 to 199
Data columns (total 4 columns):
 #   Column   Non-Null Count  Dtype
---  ------   --------------  -----
 0   size_id  200 non-null    int64
 1   width    200 non-null    int64
 2   height   193 non-null    float64
 3   label    200 non-null    object
dtypes: float64(1), int64(2), object(1)
memory usage: 6.4+ KB

#### Check for duplicates

In [60]:
df_canvasSize.duplicated().sum()

0

#### Missing Values

In [61]:
df_canvasSize.isnull().sum()

size_id    0
width      0
height     7
label      0
dtype: int64

# <font color= indigo>SQL Data Analysis

## <font color=darkcyan>Write data to SQL database

In [62]:
# Initialize a new engine that can interface with the SQLite database
engine = create_engine('sqlite:///paintings.db')

In [63]:
# Connect to the database
conn = engine.connect()

In [64]:
# Write DataFrames to SQL database
df_subject.to_sql('subject', engine, if_exists='replace', index=False)
df_museum_hrs.to_sql('museum_hrs', engine, if_exists='replace', index=False)
df_artist.to_sql('artist', engine, if_exists='replace', index=False)
df_museum.to_sql('museum', engine, if_exists='replace',index=False)
df_productSize.to_sql('product_size', engine, if_exists='replace', index=False)
df_imageLink.to_sql('image_link', engine, if_exists='replace', index=False)
df_work.to_sql('work', engine, if_exists='replace', index=False)
df_canvasSize.to_sql('canvas_size', engine, if_exists='replace', index=False)

200

In [65]:
# Load sql extension in IPython environment
%load_ext sql

# Connect to SQLite database : paintings.db
%sql sqlite:///paintings.db

## <font color=darkcyan> SQL Queries

In [66]:
%%sql
-- List all tables in the database
SELECT
    name
FROM sqlite_master
WHERE type='table';

 * sqlite:///paintings.db
Done.

[('subject',),
 ('museum_hrs',),
 ('artist',),
 ('museum',),
 ('product_size',),
 ('image_link',),
 ('work',),
 ('canvas_size',)]

### <font color=blue>1. Fetch all the paintings which are not displayed at any museums

In [67]:
%%sql
SELECT *
FROM work
WHERE museum_id IS NULL
LIMIT 10;

 * sqlite:///paintings.db
Done.

[(125752, 'Arabian Horses at Pasture', 757, 'Baroque', None),
 (125818, 'Count Halm on His Basedow Estate', 757, 'Baroque', None),
 (125763, 'Napoleon Before the Burning City of Smolensk', 757, 'Baroque', None),
 (125774, 'Peasants Resting in the Field', 757, 'Baroque', None),
 (125785, 'Portrait Oberleutnant Theodor Von Klein', 757, 'Baroque', None),
 (125796, 'The Rescue of Count Munnich', 757, 'Baroque', None),
 (125807, 'The Stable Yard', 757, 'Baroque', None),
 (24532, 'Jacob A. Stamler Departing Le Havre', 563, 'Other', None),
 (124470, 'Kaleda off Le Havre', 563, 'Other', None),
 (124479, 'R. Bell &amp; Co. Steamship Bothal in a Heavy Swell', 563, 'Other', None)]

### <font color=blue>2. Are there any museums without any paintings?

In [68]:
%%sql
SELECT *
FROM museum AS m
LEFT JOIN work AS w
    ON m.museum_id = w.museum_id
    WHERE w.museum_id IS NULL;

 * sqlite:///paintings.db
Done.

[]

### <font color=blue>3. How many paintings have an asking price which more than their regular price?

In [69]:
%%sql
SELECT
    COUNT(*) AS nr_of_paintings
FROM product_size
WHERE sale_price > regular_price;

 * sqlite:///paintings.db
Done.

[(0,)]

### <font color=blue>4. Identify the paintings whose asking price is less than 50% of its regular price

In [70]:
%%sql
SELECT *
FROM product_size
WHERE sale_price < (0.50 * regular_price)
LIMIT 20;

 * sqlite:///paintings.db
Done.

[(31780, 36, 10, 125),
 (31780, 30, 10, 95),
 (198417, 36, 30, 125),
 (198417, 30, 30, 95),
 (31974, 24, 30, 85),
 (17351, 24, 10, 85),
 (17351, 30, 10, 95),
 (17351, 36, 10, 125),
 (30947, 3024, 285, 575),
 (30947, 3226, 305, 645),
 (23710, 30, 20, 95),
 (23710, 24, 20, 85),
 (20084, 6040, 585, 1245),
 (28259, 30, 40, 95),
 (28259, 24, 40, 85),
 (28261, 24, 40, 85),
 (28261, 30, 40, 95),
 (28273, 24, 40, 85),
 (28273, 30, 40, 95),
 (28279, 48, 60, 165)]

### <font color=blue>5. Which canvas size costs the most?

In [71]:
%%sql
SELECT 
  DISTINCT(size_id),
  width,
  height,
  label
FROM (
  SELECT
    c.*,
    p.regular_price
  FROM canvas_size AS c
    INNER JOIN product_size AS p
    ON c.size_id = p.size_id
  WHERE regular_price = (SELECT MAX(regular_price) FROM product_size)) AS max_price

 * sqlite:///paintings.db
Done.

[(4896, 48, 96.0, '48" x 96"(122 cm x 244 cm)'),
 (9648, 96, 48.0, '96" x 48"(244 cm x 122 cm)')]

### <font color=blue>6. Fetch the top 10 most famous painting subject

In [72]:
%%sql
SELECT 
  subject,
  COUNT(*) AS nr_of_paintings
FROM subject
GROUP BY 1
ORDER BY nr_of_paintings DESC
LIMIT 10;

 * sqlite:///paintings.db
Done.

[('Portraits', 1070),
 ('Nude', 525),
 ('Landscape Art', 495),
 ('Rivers/Lakes', 480),
 ('Flowers', 457),
 ('Abstract/Modern Art', 399),
 ('Still-Life', 395),
 ('Seascapes', 323),
 ('Marine Art/Maritime', 268),
 ('Horses', 265)]

### <font color=blue>7. Identify the museums which are open on both Sunday and Monday.
     Display museum name and city

In [73]:
%%sql
SELECT
  mh.museum_id,
  m.name,
  m.city
FROM museum_hrs AS mh
JOIN museum AS m 
  ON mh.museum_id = m.museum_id
WHERE day = 'Sunday' 
  AND mh.museum_id IN (SELECT museum_id FROM museum_hrs WHERE day = 'Monday');

 * sqlite:///paintings.db
Done.

[(30, 'The Museum of Modern Art', 'New York'),
 (31, 'Pushkin State Museum of Fine Arts', 'Moscow'),
 (32, 'National Gallery of Victoria', 'Melbourne'),
 (35, 'The Metropolitan Museum of Art', 'New York'),
 (37, 'Museum of Grenoble', '38000'),
 (39, 'Nelson-Atkins Museum of Art', 'Kansas City'),
 (40, 'Musée du Louvre', '75001'),
 (41, 'National Maritime Museum', 'London'),
 (42, 'Museum of Fine Arts Boston', 'Boston'),
 (43, 'Rijksmuseum', 'Amsterdam'),
 (44, 'Israel Museum', 'Jerusalem'),
 (46, 'National Gallery of Art', 'Washington'),
 (47, 'National Gallery', 'London'),
 (48, 'Mauritshuis Museum', 'Den Haag'),
 (50, 'The Prado Museum', 'Madrid'),
 (51, 'The Barnes Foundation', 'Philadelphia'),
 (57, 'Van Gogh Museum', 'Amsterdam'),
 (60, 'Los Angeles County Museum of Art', 'Los Angeles'),
 (61, 'Solomon R. Guggenheim Museum', 'New York'),
 (62, 'The Tate Gallery', 'London'),
 (64, 'Museum of Fine Arts of Nancy', 'Nancy'),
 (66, 'Smithsonian American Art Museum', 'Washington'),
 (67, 'Philadelphia Museum of Art', 'Philadelphia'),
 (68, 'The Art Institute of Chicago', 'Chicago'),
 (82, 'Army Museum', 'Paris'),
 (84, 'National Gallery Prague', 'Nové Měst'),
 (85, 'Norton Simon Museum', 'Pasadena'),
 (86, 'Courtauld Gallery', 'Stran')]

### <font color=blue>8. How many museums are open every single day?

In [74]:
%%sql
SELECT 
  COUNT(*) AS everyday_museums
FROM(
  SELECT *,
    ROW_NUMBER() OVER(PARTITION BY museum_id) AS rn
  FROM museum_hrs) AS museum_hrs_days
  WHERE rn = 7;

 * sqlite:///paintings.db
Done.

[(17,)]

In [75]:
%%sql
SELECT 
  COUNT(*) AS everyday_museums
FROM (
  SELECT
    museum_id,
    COUNT(DISTINCT day) AS total_days_opened
  FROM museum_hrs
  GROUP BY 1
  HAVING total_days_opened = 7
);

 * sqlite:///paintings.db
Done.

[(17,)]

### <font color=blue>9. Which are the top 5 most popular museums?
     Popularity is defined based on most nr. of paintings in a museum

In [76]:
%%sql
SELECT  *
FROM(
  SELECT 
    m.name AS museum_name,
    COUNT(w.work_id) AS nr_of_paintings
  FROM museum AS m
  JOIN work AS w
    ON m.museum_id = w.museum_id
  GROUP BY 1) AS museum_painting_counts
ORDER BY nr_of_paintings DESC
LIMIT 5;

 * sqlite:///paintings.db
Done.

[('The Metropolitan Museum of Art', 939),
 ('Rijksmuseum', 452),
 ('National Gallery', 423),
 ('National Gallery of Art', 375),
 ('The Barnes Foundation', 350)]

### <font color=blue>10. Who are the top 5 most popular artists?
     Popularity is based on most nr. of paintings done by an artist

In [77]:
%%sql
SELECT *
FROM (
  SELECT 
    a.full_name AS artist_name,
    COUNT(w.work_id) AS nr_of_paintings
  FROM artist AS a
  JOIN work AS w
    ON a.artist_id = w.artist_id
  GROUP BY 1)AS artist_painting_counts
ORDER BY nr_of_paintings DESC
LIMIT 5;

 * sqlite:///paintings.db
Done.

[('Pierre-Auguste Renoir', 469),
 ('Claude Monet', 378),
 ('Vincent Van Gogh', 308),
 ('Maurice Utrillo', 253),
 ('Albert Marquet', 233)]

### <font color=blue>11. Display the 3 least popular canvas sizes

In [78]:
%%sql
SELECT *
FROM (
  SELECT
    c.label as canvas_label,
    COUNT(w.work_id) AS nr_of_paintings
  FROM canvas_size AS c
  JOIN product_size AS p
    ON c.size_id = p.size_id
  JOIN work AS w
    ON p.work_id = w.work_id
  GROUP BY 1
)AS canvas_label_painting_counts
ORDER BY nr_of_paintings ASC
LIMIT 3;

 * sqlite:///paintings.db
Done.

[('24" x 29"(61 cm x 74 cm)', 1),
 ('32" x 18"(81 cm x 46 cm)', 1),
 ('32" x 46"(81 cm x 117 cm)', 1)]

### <font color=blue>12. Which museum is open for the longest during a day?
     Display museum name, city and hours open and which day

In [79]:
%%sql
SELECT 
    m.name,
    m.city,
    mh.day,
    (mh.open - mh.close)  AS hrs_open
FROM museum_hrs AS mh
JOIN museum AS m
    ON mh.museum_id = m.museum_id
ORDER BY (mh.open - mh.close) DESC
LIMIT 1;

 * sqlite:///paintings.db
Done.

[('Israel Museum', 'Jerusalem', 'Friday', 8)]

### <font color=blue>13. Which museum has the most painting style?

In [80]:
%%sql
SELECT 
    m.name,
    COUNT(w.style) AS nr_of_painting_styles
FROM work AS w
JOIN museum AS m
    ON w.museum_id = m.museum_id
GROUP BY 1
ORDER BY nr_of_painting_styles DESC
LIMIT 1;

 * sqlite:///paintings.db
Done.

[('The Metropolitan Museum of Art', 939)]

### <font color=blue>14. Identify the top 5 artists whose paintings are displayed in multiple countries

In [81]:
%%sql
SELECT 
  a.full_name AS artist_name,
  COUNT(*) AS nr_of_countries_displayed
FROM museum AS m
JOIN work AS w
  ON m.museum_id = w.museum_id
JOIN artist AS a
  ON w.artist_id = a.artist_id
GROUP BY 1
HAVING nr_of_countries_displayed > 2
ORDER BY COUNT(*) DESC
LIMIT 5;

 * sqlite:///paintings.db
Done.

[('Pierre-Auguste Renoir', 272),
 ('Claude Monet', 192),
 ('Vincent Van Gogh', 142),
 ('Paul Cézanne', 125),
 ('Camille Pissarro', 95)]

### <font color=blue>15. Which country has the 5th highest nr. of paintings?

In [82]:
%%sql
SELECT 
  m.country,
  COUNT(*) AS nr_of_paintings
FROM museum AS m
JOIN work AS w
  ON m.museum_id = w.museum_id
GROUP BY 1
ORDER BY COUNT(*) DESC
LIMIT 1
OFFSET 4;

 * sqlite:///paintings.db
Done.

[('Spain', 196)]

### <font color=blue>16. Which are the 3 most popular and 3 least popular painting styles?

In [83]:
%%sql
SELECT style, nr_of_paintings, remarks
FROM (
    SELECT 
        style,
        COUNT(*) AS nr_of_paintings,
        'Most Popular' AS remarks
    FROM work
    GROUP BY style
    ORDER BY COUNT(*) DESC
    LIMIT 3
) AS most_popular
UNION ALL
SELECT style, nr_of_paintings, remarks
FROM (
    SELECT 
        style,
        COUNT(*) AS nr_of_paintings,
        'Least Popular' AS remarks
    FROM work
    GROUP BY style
    ORDER BY COUNT(*) ASC
    LIMIT 3
) AS least_popular;

 * sqlite:///paintings.db
Done.

[('Impressionism', 3078, 'Most Popular'),
 ('Post-Impressionism', 1672, 'Most Popular'),
 ('Other', 1228, 'Most Popular'),
 ('Japanese Art', 70, 'Least Popular'),
 ('Art Nouveau', 108, 'Least Popular'),
 ('Avant-Garde', 146, 'Least Popular')]